Repository wecode-bootcamp-korea/39-1st-drunkenCoders-frontend, pull requests merged in 2022-11, with the labels that each got.

#1 Add : Assets 폴더 추가
  src/assets/Cart/굳양이.jpeg
  src/assets/Footer/굳양이.jpeg
  src/assets/Login/굳양이.jpeg
  src/assets/Main/IMG_4972.jpg
  src/assets/Nav/굳양이.jpeg
  src/assets/Order/굳양이.jpeg
  src/assets/ProductDetail/굳양이.jpeg
  src/assets/ProductList/굳양이.jpeg
  src/assets/Register/굳양이.jpeg
Labels: 도움 요청, 멘토 리뷰 요청

#3 [39기 곽종범] ADD: footer 작업완료
  src/assets/footer/icon_facebook.png
  src/assets/footer/icon_instagram.png
  src/assets/footer/icon_kakao.png
  src/assets/footer/icon_naver.png
  src/assets/footer/icon_youtube.png
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/component/Sns.js
  src/components/Footer/component/Sns.scss
Labels: 멘토 리뷰 요청

#7 MODIFY: 폴더명 대소문자 수정
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
Labels: 멘토 리뷰 요청

#11 [39기 곽종범] Modify: token에 따라 로그인 로그아웃 처리
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
Labels: 멘토 리뷰 요청

#12 [39기 곽종범] ADD: top 버튼 추가
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: 멘토 리뷰 요청

#5 [39기 안상준] ADD: Product List 제작중
  public/data/ProductItemData.json
  public/data/menuData.json
  public/images/alcohol-pic/arirang.jpeg
  public/images/alcohol-pic/bartender.jpeg
  public/images/alcohol-pic/blackfriday.jpeg
  public/images/alcohol-pic/canola.jpeg
  public/images/alcohol-pic/chrysanthemum.jpeg
  public/images/alcohol-pic/coffee.jpeg
  public/images/alcohol-pic/dangjin.jpeg
  public/images/alcohol-pic/hondi.jpeg
  public/images/alcohol-pic/jadu.jpeg
  public/images/alcohol-pic/jeju.jpeg
  public/images/alcohol-pic/makurute.jpeg
  public/images/alcohol-pic/melon.jpeg
  public/images/alcohol-pic/mori.jpeg
  public/images/alcohol-pic/nimome.jpeg
  public/images/alcohol-pic/osan.jpeg
  public/images/alcohol-pic/packing.jpeg
  public/images/alcohol-pic/pakage.jpeg
  public/images/alcohol-pic/red-monky.jpeg
  public/images/alcohol-pic/rice.jpeg
  public/images/alcohol-pic/strawberry.jpeg
  public/images/alcohol-pic/sweetmama.jpeg
  public/images/arrow-down.png
  public/images/black-star.png
  public/images/check-box.png
  public/images/goodcat.jpeg
  public/images/makurute.jpeg
  public/images/sooldamhwa-logo.png
  public/images/star.png
  src/Router.js
  src/assets/Nav/goodcat.jpeg
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MyPage.scss
  src/pages/ProductList/Component/Body/ProductItem.js
  src/pages/ProductList/Component/Body/ProductItem.scss
  src/pages/ProductList/Component/Body/ProductSearch.js
  src/pages/ProductList/Component/Body/ProductSearch.scss
  src/pages/ProductList/Component/Head/Dropdown.js
  src/pages/ProductList/Component/Head/Dropdown.scss
  src/pages/ProductList/Component/Head/ProdectFilter.js
  src/pages/ProductList/Component/Head/ProductFilter.scss
  src/pages/ProductList/Component/Head/ProductMenu.js
  src/pages/ProductList/Component/Head/ProductMenu.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/styles/common.scss
Labels: 도움 요청, 멘토 리뷰 요청, 추가 기능 구현 중

#6 [39기 조은혜] 로그인 페이지 구현
  src/assets/login/icon_google.png
  src/assets/login/icon_kakao.png
  src/assets/login/icon_naver.png
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Register/Register.scss
Labels: 수정 요청

#8 [39기 곽종범] ADD: main 작업중
  public/data/reviewItem.json
  public/images/visual_1.jpg
  public/images/visual_2.jpg
  public/images/visual_3.jpg
  public/images/visual_4.jpg
  src/assets/main/icon_bizgift.png
  src/assets/main/icon_box.png
  src/assets/main/icon_cheongju.png
  src/assets/main/icon_clock.png
  src/assets/main/icon_event.png
  src/assets/main/icon_gift.png
  src/assets/main/icon_gwashilju.png
  src/assets/main/icon_jeungryuju.png
  src/assets/main/icon_next.png
  src/assets/main/icon_next_off.png
  src/assets/main/icon_next_on.png
  src/assets/main/icon_omija.png
  src/assets/main/icon_only_sooldamhwa.png
  src/assets/main/icon_pick.png
  src/assets/main/icon_prev.png
  src/assets/main/icon_prev_off.png
  src/assets/main/icon_prev_on.png
  src/assets/main/icon_speaker.png
  src/assets/main/icon_star.png
  src/assets/main/icon_star_score.png
  src/assets/main/icon_star_score_bg.png
  src/assets/main/icon_takju.png
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/component/Banner/Banner.js
  src/pages/Main/component/Banner/Banner.scss
  src/pages/Main/component/LinkList/LinkList.js
  src/pages/Main/component/LinkList/LinkList.scss
  src/pages/Main/component/Review/Review.js
  src/pages/Main/component/Review/Review.scss
  src/pages/Main/component/Timer/Timer.js
  src/pages/Main/component/Timer/Timer.scss
  src/styles/common.scss
Labels: 멘토 리뷰 요청

#13 [ADD : 39기 조은혜 로그인 페이지 구현]
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Register/Register.scss
Labels: 멘토 리뷰 요청

#10 [39기 김건우] cart 레이아웃 및 기능 구현 완료, API integration 대기 중
  public/data/cartData.json
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartItem.js
  src/pages/Login/Login.js
Labels: Conflict 해결 요청

#14 [39기 곽종범] ADD: 메인 상품 추가
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/ProductDetail/ProductDetail.js
Labels: 멘토 리뷰 요청

#15 [39기 조은혜] 회원가입 오류 수정
  src/pages/Login/Login.js
  src/pages/Register/Register.js
  src/pages/Register/Register.scss
Labels: 멘토 리뷰 요청
